baseURL = 'https://alexandrecastro.org/'
languageCode = 'en-us'
title = 'Alexandre Castro'
theme = "hyde"

[author]
  name = 'Alexandre Castro'

[params]
  description = "Documentation, ideas and opinions on what I'm currently working on."
  custom_css = ["css/overhyde.css"]

[Menus]
  main = [
      {Name = "LinkedIn", URL = "https://www.linkedin.com/in/alexandreamadocastro/"},
      {Name = "Github", URL = "https://github.com/acastro2/"}
  ]
