baseURL = 'https://alexandrecastro.tech/'
languageCode = 'en-us'
title = 'Alexandre Castro'
theme = "hyde"
enableRobotsTXT = true

[author]
  name = 'Alexandre Castro'

[params]
  description = "Insights on software architecture and platform engineering from my daily work"
  default_image = "/media/default.png"
  custom_css = ["css/overhyde.css"]

[Menus]
  main = [
      {Name = "Archive", URL = "/post"},
      {Name = "Consulting", URL = ""},
      {Name = "Mentorship", URL = ""}
  ]
