baseURL = 'https://alexandrecastro.tech/'
languageCode = 'en-us'
title = 'Alexandre Castro'
theme = ["hugo-chart", "hyde"]
enableRobotsTXT = true

[params]
  description = "Personal insights on software architecture and platform engineering."
  default_image = "/media/default.png"
  custom_css = ["css/overhyde.css"]
  author.name = "Alexandre Castro"
